#!/bin/sh

while read -r local_ref local_sha remote_ref remote_sha
do
    if [ "$local_ref" != "refs/heads/master" ] || \
       [ "$remote_ref" != "refs/heads/master" ]; then
        echo "Push rejected: only master may be published." >&2
        exit 1
    fi
done
